// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int start(
  int input_file_num,
  ffi.Pointer<ffi.Pointer<ffi.Char>> files,
);
