name: Alpha Release

on:
  push:
    tags:
      - 'v*-alpha*'

permissions:
  contents: write

env:
  FLUTTER_VERSION: '3.44.0'
  GO_VERSION: '1.26.3'

jobs:
  build-and-release-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version:  ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Decode keystore
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
      
      - name: Create AAR directory
        run: mkdir src/miru_core/android  
        
      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go get golang.org/x/mobile/bind
          gomobile version || true
          gomobile init
        working-directory: ./src/miru_core/miru-core

      - name: Build Android AAR (gomobile bind)
        working-directory: src/miru_core/miru-core/binary
        run: |
          gomobile bind -tags nosqlite -ldflags="-s -w -checklinkname=0" -o ../../android/libmiru-core.aar -target=android -androidapi 28

      - run: flutter pub get
      
      - name: Collect Apks
        run: flutter build apk --release --split-per-abi --dart-define=TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} --dart-define=TMDB_ACCESS_TOKEN=${{ secrets.TMDB_ACCESS_TOKEN }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: Release Packages
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk,build/app/outputs/flutter-apk/app-arm64-v8a-release.apk,build/app/outputs/flutter-apk/app-x86_64-release.apk"
          allowUpdates: true
          prerelease: true
          generateReleaseNotes: true

  build-and-release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Build artifacts
        run: flutter build windows --release --dart-define=TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} --dart-define=TMDB_ACCESS_TOKEN=${{ secrets.TMDB_ACCESS_TOKEN }}

      - name: Rename Release Directory Name to Miru-alpha
        run: |
          mv build/windows/x64/runner/Release build/windows/x64/runner/Miru-alpha

      - name: Zip Release
        run: Compress-Archive -Path build/windows/x64/runner/Miru-alpha -DestinationPath Miru-Alpha-windows.zip

      - name: Release Packages
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Miru-Alpha-windows.zip"
          allowUpdates: true
          prerelease: true
          generateReleaseNotes: true

  build-and-release-linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Install Dependencies
        run: pacman -Sy --noconfirm gtk3 wpewebkit git clang cmake ninja jq alsa-utils alsa-plugins tar

      - name: Config Git to Trust All Repositories
        run: git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Build artifacts
        run: flutter build linux --release --dart-define=TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} --dart-define=TMDB_ACCESS_TOKEN=${{ secrets.TMDB_ACCESS_TOKEN }}
        
      - name: Rename Release Directory Name to Miru-alpha
        run: mv build/linux/x64/release/bundle build/linux/x64/release/Miru-alpha
        
      - name: Tar Release
        run: tar -czvf Miru-Alpha-linux.tar.gz -C build/linux/x64/release Miru-alpha
        
      - name: Release Packages
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Miru-Alpha-linux.tar.gz"
          allowUpdates: true
          prerelease: true
          generateReleaseNotes: true
